### ISSUE TITLE
Missing _includes/google-analytics.html

### ISSUE THREAD

**Issue by mnafisalmukhdi1** [brennanbrown/purelog#7]
First of all, sorry for my English grammar, but I tried to describe the problem, the best as I can.

In `config.yml` there are `google_analytics` that I think it's can be filled by something like. UA-XXX

So, when I fill that and try to run Github Pages, a failure happened. And, I'm trying to figure out what is the problem.

In `_includes/head.html` we could find:
`{%- if site.google_analytics -%}
{%- include google-analytics.html -%}
{%- endif -%}`

However, there is none of `_includes/google-analytics.html`.

So, that's it. Thanks for your template.

**Comment by brennanbrown** [comment]
Your English is great! Thanks for commenting on this. I just fixed it.
